docs(api): fix typo in attachTo anchor tag within isVisible
vuejs/test-utils pull request #2351
Opened 2024-02-22 10:03 UTC by matusekma

There is a typo in the anchor tag that links from the isVisible documentation to the attachTo documentation.

2024-02-22 13:19 UTC, cexbrayat requested changes

2024-02-26 10:20 UTC, matusekma commented on docs/api/index.md
> +`isVisible()` only works correctly if the wrapper is attached to the DOM using [`attachTo`](#attachTo)
Thank you! There is no equivalent in the French docs. I speak some French so I can try to add it. What's you suggestion?

2024-02-26 15:36 UTC, cexbrayat commented on docs/api/index.md
> +`isVisible()` only works correctly if the wrapper is attached to the DOM using [`attachTo`](#attachTo)
Yes, it would be rgeat to add the warning there as well 👍

2024-03-27 13:23 UTC, cexbrayat approved these changes
LGTM, thanks @matusekma !

2024-03-27 13:25 UTC, merged