feat: add Chinese docs translation
vuejs/test-utils pull request #2552
Opened 2024-11-22 10:08 UTC by DDDDD12138

### Description
Add Chinese documentation, detailed comparison with the original English can be found in this [commit](https://github.com/vuejs/test-utils/commit/3f3f8b7041f6581a9905da99d5620a3ce58a9fc1).

### Preview
![image](https://github.com/user-attachments/assets/e509e0a3-89a5-42c3-b872-b133299cf3c6)
![image](https://github.com/user-attachments/assets/9a0f1dfe-9866-45b5-b18a-f5898bf0541f)
![image](https://github.com/user-attachments/assets/a9f3ab87-ac94-4843-a6e7-36a14973715a)

2024-12-02 03:26 UTC, Jinjiang requested changes
Well, after reviewing some docs, I've found quite a lot of formatting issues. I would recommend you to refer to this [Chinese translation guide](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5) for more details. And in practice, you can feel free to run [zhlint](https://www.npmjs.com/package/zhlint), the tool we use for Vue Chinese docs, on your translation files. Usually for most of the issues, this tool can help you to figure them out and fix them. We can discuss further if you have any questions in any particular cases.

After solving the formatting issues, we can merge it ahead (probably with a "in review" marks on the pages somewhere) and then review the docs piece by piece as the second step.

Thanks.

2024-12-02 10:28 UTC, DDDDD12138 commented
ok, I'll deal with it later.

2024-12-02 11:42 UTC, DDDDD12138 commented on docs/zh/README.md
> +# Vue Test Utils
Does Chinese not require this file? I referred to fr, and it added this file (although I think I forgot to translate it).

2024-12-03 10:45 UTC, Jinjiang commented on docs/zh/guide/essentials/a-crash-course.md
> +我们首先导入 `mount` —— 这是在 VTU 中渲染组件的主要方式。使用 `test` 函数声明一个测试，并给出简短的描述。`test` 和 `expect` 函数在大多数测试运行器中是全局可用的 (此示例使用 [Jest](https://jestjs.io/))。如果 `test` 和 `expect` 看起来令人困惑，Jest 文档中有一个[更简单的示例](https://jestj
中文破折号两边不需要空格 (因为是全角符号)，下同

2024-12-03 10:45 UTC, Jinjiang commented on docs/zh/guide/advanced/async-suspense.md
> +让我们重用来自 [事件处理](../essentials/event-handling) 的 `<Counter>` 组件，唯一的变化是我们现在在 `template` 中渲染 `count`。
```suggestion
让我们重用来自[事件处理](../essentials/event-handling)的 `<Counter>` 组件，唯一的变化是我们现在在 `template` 中渲染 `count`。
```

md 标记内外都是中文或其它全角字符的情况下不需要空格，下同

2024-12-03 10:47 UTC, Jinjiang commented on docs/zh/README.md
> +# Vue Test Utils
Not necessary unless you have anything extra to write about as a translator.

2024-12-03 10:50 UTC, Jinjiang commented on docs/.vitepress/theme/index.mts
> +  zh: '翻译与${date}的文档同步，其 commit 的哈希值为 <code>${hash}</code>。'
```suggestion
  zh: '该翻译已同步到了 ${date} 的版本，其对应的 commit hash 是 <code>${hash}</code>。'
```

I just synced the translation in other official libs like pinia and router. And also the date needs spaces around. 🙏

2024-12-03 19:47 UTC, veaba reviewed
文件太大没法加 sug，斜体使用

```md
另外补充：vue-router.md L289 部分。
```suggestion
然而，在这种情况下，我们没有可以等待的 *hasNavigated* 钩子。一种替代方法是使用从 Vue Test Utils 导出的 `flushPromises` 函数：
```

添加太大 500 了。
```

2024-12-03 19:47 UTC, veaba commented on docs/zh/migration/index.md
> +这是一个针对来自 VTU 1 的用户的表格，比较 API。
```suggestion
这是一个针对来自 VTU 1 用户的表格，其比较了两者的 API。
```

2024-12-03 19:47 UTC, veaba commented on docs/zh/guide/advanced/reusability-composition.md
> +要测试这个组合式函数，你可以在测试中创建一个简单的 `TestComponent`。`TestComponent` 应该以与真实组件相同的方式使用组合式函数。
```suggestion
要测试这个组合式函数，你可以在测试中创建一个简单的 `TestComponent`。`TestComponent` 应该与真实组件一样的方式使用组合式函数。
```
优化表达

2024-12-03 19:47 UTC, veaba commented on docs/zh/guide/advanced/reusability-composition.md
> +Vue 提供了一种通过 `provide` 和 `inject` 将 props 传递给所有子组件的方法。测试这种行为的最佳方式是测试整个树 (父组件 + 子组件)。但有时这并不可能，因为树结构过于复杂，或者你只想测试单个组合式函数。
```suggestion
Vue 提供了一种通过 `provide` 和 `inject` 将 props 传递给所有子组件的方法。测试这种行为的最佳方式是测试整个树 (父组件+子组件)。但有时这并不可能，因为树结构过于复杂，或者你只想测试单个组合式函数。
```
中文之间的空格使用

2024-12-04 04:45 UTC, Jinjiang commented on docs/zh/guide/advanced/reusability-composition.md
> +Vue 提供了一种通过 `provide` 和 `inject` 将 props 传递给所有子组件的方法。测试这种行为的最佳方式是测试整个树 (父组件 + 子组件)。但有时这并不可能，因为树结构过于复杂，或者你只想测试单个组合式函数。
都说得通吧，这里我个人倾向是有空格的，因为加号相当于是半角符号

2024-12-04 07:08 UTC, DDDDD12138 commented on docs/zh/guide/advanced/reusability-composition.md
> +Vue 提供了一种通过 `provide` 和 `inject` 将 props 传递给所有子组件的方法。测试这种行为的最佳方式是测试整个树 (父组件 + 子组件)。但有时这并不可能，因为树结构过于复杂，或者你只想测试单个组合式函数。
那就都保持这样吧？带上空格也显得不会那么挤

2024-12-04 07:09 UTC, DDDDD12138 commented
> 添加太大 500 了。

这个指的是啥？我这边好像没显示出来🤔

2024-12-04 07:35 UTC, veaba commented
> > 添加太大 500 了。
> 
> 这个指的是啥？我这边好像没显示出来🤔

那个 vue-router.md 文件太大，没办法对指定位置添加 Suggetion，Github 报 500了。

改动部位：`_hasNavigated_` 改为 `*hasNavigated*` 就可以了。


@Jinjiang  我这边 review 结束了，再交叉检查下应该可以了。

2024-12-05 10:11 UTC, Jinjiang approved these changes

2024-12-05 10:13 UTC, Jinjiang commented
![image](https://github.com/user-attachments/assets/78bc0eaf-edb8-4185-9e05-54a647ef9ef2)

I've added these in-review labels and created this epic issue #2561 for further review.

For this PR I will merge soon. Thanks all.

2024-12-05 10:13 UTC, merged